### ISSUE TITLE
Class "App\Providers\NovaLanguageEditor" not found

### ISSUE THREAD

**Issue by mehak-softuvo** [crayon1337/Nova-Language-Management#2]
Hi while doing this following 

/**
 * Get the tools that should be listed in the Nova sidebar.
 *
 * @return array
 */
public function tools()
{
    NovaLanguageEditor::make();
}

Result

Class "App\Providers\NovaLanguageEditor" not found

**Comment by mohamedary** [comment]
Sorry I just saw your issue. If you haven't been able to fix the issue yet. Please import NovaLanguageEditor at the top of your NovaService provider like below:

use Crayon\NovaLanguageEditor\NovaLanguageEditor;
